### PR TITLE
adv conf: add ROOT_CHECK_AVOID for container.

### PR DESCRIPTION
**Pull request by fbourqui**
import_gs only once at start

The ./gravity-sync.sh check that it's deployed with it's own user, but for container deployment it's a nuisance, to install a user and gave it password less sudo power, witch result with the same security risk as running as root.

### CODE REVIEW

**Comment by vmstan** [comment]
The import_gs function is necessary to read the .conf file, if it's removed from the various functions they won't be able to read the file for environment settings. Additionally, there are a few functions where it's not necessary to import these settings (update, version) as well as the configuration tool itself where it's not loaded until after you verify you don't want to use the old one. That's why it's called within in the separate functions.

As far as the root avoidance check, are the containers running as root already within themselves? How do they handle the requests for sudo elevation.

**Comment by fbourqui** [comment]
Hello,

Yes the container are lxd container (ubuntu running on ubuntu) where only root user exist, could create another user but I do not see the point, as this new user must be allowed to sudo without password, ...
root user is allowed to sudo, even if it's not necessary. 

In bash when you load a variable in the main "function" those variable are global and can be read and modified by all function.

Check my version even the config option will diplay the current config.

Cheers,
Fred

**Comment by fbourqui** [comment]
I also added the possibility to call the automation with 2 parameters.
I fully deploy my 2 pihole with ansible, from lxd container creation, pihole deployment, letsencrypt TLS key, keepalived, and gravity script,  and I  also used the automation option to schedule sync and backup.

**Comment by fbourqui** [comment]
Hello,



thanks for merging the changes, but you "killed" the ROOT_CHECK_AVOID functionally by removing my import_gs (before testing the value ).



May I suggest you read the following article about bash variables scope:

https://www.thegeekstuff.com/2010/05/bash-variables/



Particularly:

Example 6. Global and Local Bash Variables



running import_gs, only once before my test is the correct way, ...



Cheers,

Fred





---- On Thu, 16 Jul 2020 20:10:01 +0200 Michael Stanclift <notifications@github.com> wrote ----





Merged https://github.com/vmstan/gravity-sync/pull/64 into development.

**Comment by vmstan** [comment]
Yes I reverted that part of it back because it was breaking the output of status messages at the top of the script execution, but I understand where it would need to be called prior to your check, and can make the adjustments necessary and reimplement.

**Comment by vmstan** [comment]
It's back in there the way you had it, flipped around the lines of Evaluating Arguments because that's what was messing up the status output. Moved the SSH connection and validation bits that were in import_gs to a different function to run only when needed. I pushed this as 2.1.7 to the master branch along with the rest of what was supposed to be 2.1.6.

You're the first time I've ever had anyone do a PR against my code, as I'm still learning how to GitHub, so forgive me for this being a little messy.

**Pull request merged**
