### PR TITLE
Docker image: Pihole + gravity-sync + openssh-server in one image, named 'sync-hole'

### PR DESCRIPTION
**Pull request by systemofapwne**
This PR includes changes, that will bundles the following into one single docker image.
- pihole
- gravity-sync
- openssh-server

With these packages combined, it becomes a drop-in replacement for pihole. Syncing pihole never was easier!

I named this bundle `sync-hole`.

Documentation has been added and the current docker-image is 100% compatible to 'classic' gravity-sync setups.

NOTE: This PR relies also on the changes of my previous PR: https://github.com/vmstan/gravity-sync/pull/384 but might already be in this PR. I suggest, you first accept the other PR before this one here.
NOTE: Since my container requires the mentioned PR changes above, I have changed the upstream url in /etc/gravity-sync/.gs via the Dockerfile to my own gravity-sync fork. Please remove the following line, when you accept both PRs: https://github.com/systemofapwne/gravity-sync/blob/eef56b1922d44c1354c2d082a095de8ebcbfa4f9/docker/Dockerfile#L8

It would also be extremely nice, if you could supply an "official" `sync-hole` image to dockerhub.

If you think, that these changes are too much for your project, that so far only is about `gravity-sync` and not about bundling it with pihole & openssh-server via a docker image: Let me know! I would then start a dedicated repo with CI against automated generation of images to dockerhub. But IMHO, this project here should be available fully dockerized and bundled with pihole.

### CODE REVIEW

**Comment by wblew** [comment]
Very nice work!

**Comment by zenzip** [comment]
would be great include unbound also in this bundle, would be perfect!

**Comment by systemofapwne** [comment]
Is unbound now part of official PiHole? If not, you can build your own docker container and add unbound on top of it. Or even better: Build a secondary docker container just for unbound that either uses this piHole container as source (or feeds this docker container as primary DNS).

**Comment by holly79** [comment]
I used the code from @systemofapwne and it works like a charm.  Thanks @systemofapwne !

I hope that your PR will be merged and other users will be able to use it more easily.

**Comment by github-cli** [comment]
looking forward to this... installing on one of the systems itself is not an option for me

**Comment by Jarsky** [comment]
I wouldnt include unbound in this package either; Its extremely easy to spin up an Unbound docker.
If youre using Docker Swarm or Kubernetes just have multiple images in the stack to deploy together.
Not everyone is using Unbound either; personally im using Cloudflared so it would be a pain/redundant to have Unbound in there.

**Comment by vmstan** [comment]
Effective July 26, 2024, this project has been retired. Thank you for your use and enthusiasm for a project that began as a few lines of bash in a Slack channel and envolved into something far more complex, and used by many thousands of Pi-hole enthusiasts over the last four years.

**Pull request closed without merging**
