### PR TITLE
4.0.0

### PR DESCRIPTION
**Pull request by vmstan**
## The Re-Release

Gravity Sync 4 is an extensive rewrite of the application. There is not a single function, variable, or chunk of code that has gone untouched.

In the past I've always tried to make sure that anyone who wanted to update, would not have to do much more than occasionally reapply automation jobs to take advantage of new features. The effect of this made me reliant on flawed or shortsighted decisions that I'd made two years ago, and forced building all new features on top of (or within) the structure of those decisions. 

Gravity Sync 4 is a fresh start.

#### Beta Installer

1. The beta is overall stable, but you're signing up to run the development branch so it's also possible it could break depending on many things, including your setup.
2. You don't have to fully remove your previous Gravity Sync install to run the beta, but you should remove any automated Gravity Sync replication jobs, prior to installing the beta.
3. Please read through the changes here, before you install this, to understand what might be required!
4. Feedback is welcome. 

```
curl -sSL http://gravity.vmstan.com/beta | GS_DEV=4.0.0 bash
```

#### Tested Platforms

While it's not possible to test Gravity Sync on all the places it's technically able to run, this chart outlines the places where it has been tested. Pi-hole has a list of supported platforms if it's a default install, but if your Pi-hole instance is running in a container, it provides more flexibility.

| Distro   | Version       | Pi-hole Type    | Notes |
|----------|---------------|-----------------|-----------------|
| CentOS | 8 Stream | Default/Docker | |
| Debian | 11 | Default/Docker | |
| Debian | 10 | Default/Docker | |
| DietPi | 8.3 | Default | |
| Fedora | 35 | Docker | |
| Photon | 4.0 | Docker | |
| Raspbian | 11 | Default/Docker | |
| Rocky | 8.5 | Docker | |
| Ubuntu | 21.10  | Default/Docker  | |
| Ubuntu | 20.04 | Default/Docker | |

### Rethought Installation

The Gravity Sync installer has been rewritten to accommodate for both new installations and upgrades. (Upgrading only after a successful migration to 4.0, see below.) Previously it would detect existing installs and refuse to complete. There is also a dedicated update script that can be used to fix a broken deployment by executing `bash /etc/gravity-sync/.gs/update.sh` but should only be required if for some reason `gravity-sync update` has failed.

### Rearchitected Deployment

The architecture and installation have been simplified so that Gravity Sync is installed on the pair of Pi-hole boxes that you want to use it. There is no more primary or secondary Pi-hole, and both sides run replication jobs as peers. When either side detects changes to your Pi-hole configuration, they are sent to the peer. 

Automation jobs are set to run at rotating-randomized times to avoid collisions, and to prevent continuous resyncing the hashes that were previously only saved to one instance are now also sent to the peer at the end of a successful replication event.

With automation fully enabled, changes to either Pi-hole will usually result in both sides reflecting the change within 5 minutes. However if you're making large changes you want to monitor, or just feeling impatient, you can still manually run a replication job anytime.

If you only want to run Gravity Sync on one Pi-hole, that's still fine too. An optional "peerless" mode will detect the absence of a configuration at the remote site and bypass the hash sync. A warning will appear in the Gravity Sync console output to configure at the remote side for full functional, but can be ignored. (This also should allow folks who replicate between more than two Pi-hole instances to have multiples syncing to a single source of truth.)

### Relocated Executables

Gravity Sync previously required itself to live in the user's `$HOME` directory. Alternatively, if it was installed as the `root` user, Gravity Sync _could_ live in any self contained folder on the system. 

In 4.0, Gravity Sync now lives in `/usr/local/bin` (along side `pihole`) and the configuration files and job logs are contained in the `/etc/gravity-sync` folder. This change to the configuration folder should make containerizing Gravity Sync easier in the future. (hint, hint)

The main script has been renamed from `gravity-sync.sh` to `gravity-sync` and due to it's relocation, has the nice effect of letting you execute just `gravity-sync` from anywhere in the system. Said another way, you no longer have to run `./gravity-sync.sh` from the Gravity Sync folder in `$HOME` anytime you want to manually run it. 

### Resimplified Backups

Along with the removal of the dedicated backup and restore features that happened in 3.5, in 4.0 the backup functions are resimplified in that backup files are no longer timestamped, so jobs that no longer complete successfully will not continue to write new backup files each time, until the hard drive has been filled.

- All data backup operations have moved to the `/tmp` folders on both the local and remote Pi-hole. 
- All backup files have the extension `.gsb` appended to them during processing. This replaces the various `.backup`, `.pull`, `.push` files of previous versions. 

The amount of write activity, network traffic, and overall execution time has been reduced by cutting down on the number of backup data copies that are created, especially during push operations.

### Reduced Dependence

The dependency on a standalone copy of SQLite3 has been removed. Gravity Sync now uses the integrated SQLite3 instance that is built into Pi-hole's FTL component (`pihole-FTL sql`) which also removes impediments for folks wanting to install Gravity Sync on systems that didn't have the ability to also install SQLite3. 

All cron related automation functions have been removed. The systemd based replication function that was introduced in 3.7 comes forward, with further enhancements. This means packages like 'cronie' are no longer needed on systems that lacked a built in crontab.

### Really New

In addition to everything above there are a few new functions.

- `gravity-sync purge` now uninstalls and completely removes Gravity Sync from the system. It previously only reset the installation to new.
- `gravity-sync disable` will fully stop and remove all automation jobs in systemd.
- `gravity-sync monitor` will let you watch the real time status of replication jobs.

If DNS Records and CNAME Records are detected at either side, they are replicated. Previously these functions required you to opt-in to replicating these, but this was done because their functionality was added after the initial release of Gravity Sync in 2020.

### Required to Upgrade

There are two ways to upgrade to Gravity Sync 4.

#### Fresh Install

Using the curl to bash one liner listed above, you will deploy a new install of Gravity Sync 4 to both of your existing Pi-hole. Any current Gravity Sync configuration will be ignored. 

You will need to generate a new configuration file using `gravity-sync config` but because the configuration workflow has been completely redone, in most cases you will only need to provide the IP address & username/password for your remote Pi-hole. Gravity Sync will automatically detect if you have a containerized instance of Pi-hole and prompt for the name of the instance(s). Once this is provided it will automatically detect the bind mounts in use for Pi-hole's two /etc directories. It's possible to have your new configuration generated in less than a minute. 

Gravity Sync now uses a dedicated SSH key for connection to remote Pi-hold instances. This key is stored as `/etc/gravity-sync/gravity-sync.rsa` and should be used only for Gravity Sync. The configuration utility will create the new key file. Existing default id_rsa key associations to remote servers can be safely deleted/removed unless they're associated with some other process.

#### Migrate Existing Configuration

From your existing Gravity Sync folder, running any version 3.1 or higher, run `./gravity-sync.sh update` and the the version 4.0 code will temporarily come into the existing folder. At this point `./gravity-sync.sh` is the migration tool to move you to the version 4.0 format. 

Run `./gravity-sync.sh` **again** and a new Gravity Sync 4 installation will be laid down for you and your existing configuration, logs, SSH key, and hashes will be migrated to the fresh install. Legacy backup files are not retained. At the end of a successful script execution the legacy Gravity Sync folder will be deleted, so you may need to run a `cd ~` to get yourself out of the now deleted folder.

Many of what were termed "Hidden Figures" as advanced configuration options have been removed, as they're no longer supported or the logic behind them being necessary have changed. So only the configuration settings relevant to 4.0 will be transferred.

Your automation settings will be defaulted to nothing. You will want to run a `gravity-sync compare` to make sure your migration was successful.

At this point you will want to perform a fresh install of Gravity Sync **on your other Pi-hole** to enable peer mode and hash sharing. Once that is successful enable automation on both nodes using `gravity-sync auto`.

### CODE REVIEW

**Comment by sawsanders** [comment]
First, thank you for this software. I have used it for a while and it works great. I appreciate the time you have put into it.

I have a question and one comment on a potential problem:

So to clarify, for V4, we need to install on both PiHoles? Prior to V4, it was only installed on one of my PiHoles, the "secondary".

Also, during installation on the primary, which hasn't had a gravity-sync install before, I had to run with sudo for it to add the remote ssh key correctly. The installation completed without installing the key but when I ran a "gravity-sync push" it refused to add the key and finish until I ran with sudo.

**Comment by vmstan** [comment]
That's correct. It installs on both now.

What OS is the one that gave you troubles with the key running?

**Comment by sawsanders** [comment]
Output from the info command:

pi@pi:~$ gravity-sync info
∞ Initalizing Gravity Sync (4.0.0)
✓ Loading gravity-sync.conf
✓ Evaluating arguments: INFO
∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞
Local Software Versions
Pi-hole
  Pi-hole version is development v5.9-20-ga48750e2 (Latest: v5.9.1)
  AdminLTE version is devel v5.11-82-g6669b4c8 (Latest: v5.11)
  FTL version is development vDev-6576eb6 (Latest: v5.14)
Description:	Ubuntu 21.10
Linux 5.13.0-1022-raspi aarch64
bash 5.1.8(1)-release
OpenSSH_8.4p1 Ubuntu-6ubuntu2.1, OpenSSL 1.1.1l  24 Aug 2021
rsync  version 3.2.3  protocol version 31
Sudo version 1.9.5p2
git version 2.32.0

Global Instance Settings
DNS Replication: Enabled (default)
CNAME Replication: Enabled (default)
Verify Operations: Enabled (default)
Ping Test: Enabled (default)
SSH Port: 22 (default)
SSH Keyfile: /etc/gravity-sync/gravity-sync.rsa
Automated Replication: Disabled

Local Instance Settings
Local Hostname: pi
Local Pi-hole Type: default
Local Pi-hole Config Directory: /etc/pihole
Local DNSMASQ Config Directory: /etc/dnsmasq.d
Local Gravity Sync Binary: /usr/local/bin/gravity-sync
Local Gravity Sync Config Directory: /etc/gravity-sync
Local Pi-hole Binary Directory: /usr/local/bin/pihole
Local File Owner Settings: pihole:pihole

Remote Instance Settings
Remote Hostname/IP: 192.168.10.21
Remote Username: pi
Remote Pi-hole Type: default
Remote Pi-hole Config Directory: /etc/pihole
Remote DNSMASQ Config Directory: /etc/dnsmasq.d
Remote Pi-hole Binary Directory: /usr/local/bin/pihole
Remote File Owner Settings: pihole:pihole
∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞
∞ Gravity Sync INFO exited after 1 seconds

**Comment by vmstan** [comment]
Thanks, I’ll run through a fresh setup on Ubuntu and see what’s up. Is the other system also running 21.10?

**Comment by sawsanders** [comment]
Yes

**Comment by ytsejam1138** [comment]
Working great on my two Pi-Holes running on Raspberry Pi Zero 2's.

**Comment by JYewdall** [comment]
pi@localhost:~ $ gravity-sync update
∞ Initalizing Gravity Sync (4.0.0)
✓ Evaluating arguments: UPDATE
∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞
/usr/local/bin/gravity-sync: line 2272: /usr/bin/bash: No such file or directory
∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞
∞ Gravity Sync UPDATE completed after 0 seconds
pi@localhost:~ $ bash /etc/gravity-sync/.gs/update.sh
Pulling from origin/4.0.0
Fetching origin
HEAD is now at e2c64a3 rerandom
pi@localhost:~ $

 gravity-sync info
∞ Initalizing Gravity Sync (4.0.0)
✓ Loading gravity-sync.conf
✓ Evaluating arguments: INFO
∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞∞
Local Software Versions
Pi-hole
  Pi-hole version is v5.9.1 (Latest: v5.9.1)
  AdminLTE version is v5.11 (Latest: v5.11)
  FTL version is v5.14 (Latest: v5.14)
Description:    Raspbian GNU/Linux 10 (buster)
Linux 5.10.103-v7+ armv7l
bash 5.0.3(1)-release
OpenSSH_7.9p1 Raspbian-10+deb10u2+rpt1, OpenSSL 1.1.1n  15 Mar 2022
rsync  version 3.1.3  protocol version 31
Sudo version 1.8.27
git version 2.20.1

**Comment by vmstan** [comment]
>  line 2272: /usr/bin/bash: No such file or directory

@JYewdall reference should be fixed, manually run updater for latest

**Comment by vmstan** [comment]
> Also, during installation on the primary, which hasn't had a gravity-sync install before, I had to run with sudo for it to add the remote ssh key correctly. The installation completed without installing the key but when I ran a "gravity-sync push" it refused to add the key and finish until I ran with sudo.

I think the issue here is the /etc/gravity-sync folder needs permissions set differently depending on the distro. I've pushed a change to the installer to set it as chmod 775.

**Comment by vmstan** [comment]
I've pushed some changes today that remove the options to not sync DNS and CNAME records. It didn't seem like these were being used much and led to more confusion during setup for most folks. At one point Pi-hole didn't include the files at install but they fixed that many versions back.

If the entries exist on either Pi-hole they'll be synced out of the box.

The only folks that I anticipate possible bugs with this are those who don't have any local CNAMEs configured. I'm working on testing various setups now.

**Comment by vmstan** [comment]
The md5 hash file that tracks the previous successful replication job have been broken up into separate files for each tracked file. This should allow for more flexibility in the future.

**Comment by ZachChristensen28** [comment]
The only issue I have been running into from upgrading is that a [legacy alias definition from the previous install](https://github.com/vmstan/gravity-sync/blob/master/includes/gs-config.sh#L485) hard codes the location of the gravity-sync script to my home directory opposed to /usr/local/bin/gravity-sync. This causes issues when trying to run the gravity-sync command without specifying the full path to the new gravity-sync location.

**Comment by vmstan** [comment]
Yes thank you I'd been meaning to add a removal of that to the installer.

**Pull request merged**
